# Generated by Django 2.2 on 2021-05-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_auto_20210529_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='userApp.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchased_at',
            field=models.DateTimeField(null=True),
        ),
    ]
