# Generated by Django 2.2 on 2021-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_auto_20210529_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_revenue',
            field=models.FloatField(default=0.0),
        ),
    ]
